name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      CI: true
      SSHOOGR_RELEASE: true
    steps:
      - name: Checkout sshoogr
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout sshoogr-parent
        uses: actions/checkout@v2
        with:
          repository: sshoogr/sshoogr-parent
          path: sshoogr-parent

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}
          restore-keys: |
            ${{ runner.os }}-gradlew-

      - name: Publish sshoogr-parent
        working-directory: ./sshoogr-parent
        run: |
          chmod +x gradlew
          ./gradlew publishToMavenLocal

      - name: Release
        working-directory: ./main
        run: |
          chmod +x gradlew
          ./gradlew bintrayUpload
